# Generated by Django 4.0.5 on 2022-10-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
